import discord
import random
import asyncio
from discord.ext import commands, tasks
from datetime import datetime, timedelta
import pytz

icebreaker_questions = [
    "If video game characters were real, which one do you think would make the best roommate and why?",
    "If you could create a video game based on your life, what would the title be and what would the objective be?",
    "If you were a character in a video game, what special power or ability would you have and how would you use it to your advantage?",
    "If you could live inside any computer program or software, which one would it be and why?",
    "If you were trapped in a virtual reality game for a week, which era or setting would you choose for the game to take place in?",
    "If you had to assemble a team of three fictional AI companions from different video games to help you solve real-world problems, who would you choose and why?",
    "If you could enhance any piece of technology from a video game and make it a reality, what would it be and how would it improve your daily life?",
    "If you could transport yourself into the world of any classic arcade game, which one would you choose and how would you fare in its challenges?",
    "If your life was a point-and-click adventure game, what would be the first puzzle you'd encounter and how would you solve it?",
    "If you could design your own virtual reality game, what would the central theme or concept be and why?",
    "If you could upload your consciousness into a computer like in a science fiction game, what would be the first thing you'd do in your new digital form?",
    "If you had to survive a zombie apocalypse using only items found in computer games, what would be your go-to weapon and why?",
    "If you could bring one piece of futuristic technology from a video game into the present day, what would it be and how would it revolutionize society?",
    "If video game characters were real, which one do you think would make the best roommate and why?",
    "If you could create a video game based on your life, what would the title be and what would the objective be?",
    "If you were a character in a video game, what special power or ability would you have and how would you use it to your advantage?",
    "If you could live inside any computer program or software, which one would it be and why?",
    "If you were trapped in a virtual reality game for a week, which era or setting would you choose for the game to take place in?",
    "If you had to assemble a team of three fictional AI companions from different video games to help you solve real-world problems, who would you choose and why?",
    "If you could enhance any piece of technology from a video game and make it a reality, what would it be and how would it improve your daily life?",
    "If you could transport yourself into the world of any classic arcade game, which one would you choose and how would you fare in its challenges?",
    "If your life was a point-and-click adventure game, what would be the first puzzle you'd encounter and how would you solve it?",
    "If you could design your own virtual reality game, what would the central theme or concept be and why?",
    "If you could upload your consciousness into a computer like in a science fiction game, what would be the first thing you'd do in your new digital form?",
    "If you had to survive a zombie apocalypse using only items found in video games, what would be your go-to weapon and why?",
    "If you could bring one piece of futuristic technology from a video game into the present day, what would it be and how would it revolutionize society?",
    "If you could have any fictional character from a video game as your best friend, who would it be and why?",
    "If you could live in the world of any video game for a week, which game would you choose and what would you do?",
    "If you could be a playable character in any video game, which one would you choose and why?",
    "If you could swap lives with a character from a video game for a day, who would it be and what would you do differently?",
    "If you could pick one video game to play for the rest of your life, which one would it be and why?",
    "If you could have any special power or ability from a video game, which one would you choose and how would you use it in your daily life?",
    "If you could attend any fictional event from a video game, which one would it be and what would you hope to experience?",
    "If you could visit any video game's iconic location, where would you go and what would you do there?",
    "If you could bring any video game character to life for a day, who would it be and what would you do together?",
    "If you could create a spin-off video game for any existing series, which one would it be and what would it focus on?",
    "If you could live in any video game's universe but as a different character, who would you be and why?",
    "If you could erase your memory of any video game to experience it for the first time again, which one would you choose?",
    "If you could have any video game's soundtrack playing in the background of your life, which one would you pick?",
    "If you could spend a day with the characters from any video game, which one would you choose and what would you all do together?",
    "If you could bring back any discontinued video game series for another installment, which one would it be and why?",
    "If you could be a playable character in any video game's multiplayer mode, which one would you choose and how would you strategize to win?",
    "If you could live in any video game's world but had to follow its rules, which game would you pick and how would you adapt?",
    "If you could have any video game character as your mentor, who would it be and what advice would you hope to receive?",
    "If you could rewrite the ending of any video game, which one would you change and how would you end it instead?",
    "If you could have a crossover DLC between two video games, which ones would you choose and how would the gameplay merge?",
    "If you could be roommates with a character from any video game, who would it be and why?",
    "If you could join the cast of any video game series, which one would you choose and what role would you play?",
    "If you could swap lives with a character from a video game for a week, who would it be and why?",
    "If you could have any fictional job from a video game, what would it be and why?",
    "If you could live in any video game's house or apartment, which one would you choose and why?",
    "If you could be a part of any video game's squad or team, which one would you join and why?",
    "If you could travel back in time to be on the development team of any classic video game, which one would you pick and why?",
    "If you could solve a quest or mystery with any video game protagonist, who would you choose to partner with and why?",
    "If you could have any video game character's wardrobe, whose closet would you raid and why?",
    "If you could attend any video game's in-game event or festival, where would you go and what would you do?",
    "If you could be a contestant on any in-game competition or tournament, which one would you choose and why?",
    "If you could have any video game character as your AI companion, who would it be and why?",
    "If you could be a guest NPC in any video game's world, which one would you choose and what role would you play?",
    "If you could have any video game character's catchphrase as your own, which one would you choose and when would you use it?",
    "If you could throw a party inspired by any video game, which one would you pick and how would you decorate?",
    "If you could rewrite the tutorial level of any video game, which one would you choose and how would you change it?",
    "If you could have any video game character's talent or skill, which one would you choose and why?",
    "If you could have any video game character's significant other, who would you choose and why?",
    "If you could have any video game character's friendship and/or nemesis, who would you choose and why?",
    "If you could have any video game character's catchphrase, which one would you choose and why?",
    "If you could have any superpower, what would it be and why?",
    "What's the most adventurous thing you've ever done?",
    "If you could travel anywhere in the world right now, where would you go and why?",
    "What's your favorite book/movie/TV show and why?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the best piece of advice you've ever received?",
    "If you could only eat one cuisine for the rest of your life, what would it be?",
    "What's the most interesting thing about you that most people don't know?",
    "If you could switch lives with someone for a day, who would it be and why?",
    "What's your favorite hobby or pastime?",
    "If you could instantly become an expert in something, what would it be?",
    "What's the craziest dream you've ever had?",
    "If you could have any animal as a pet, what would it be?",
    "What's your guilty pleasure?",
    "If you could time travel, would you go to the past or the future?",
    "What's your favorite thing about your current job or studies?",
    "If you could have any talent, what would it be?",
    "What's your favorite way to relax after a long day?",
    "If you could meet any fictional character, who would it be and why?",
    "What's the most memorable gift you've ever received?",
    "If you could live in any era of history, which one would you choose?",
    "What's your favorite type of music and why?",
    "If you could only keep five possessions, what would they be?",
    "What's the best trip you've ever been on?",
    "If you could have any job in the world, what would it be?",
    "What's your favorite season and why?",
    "If you could have any famous artist paint your portrait, who would it be?",
    "What's your biggest fear?",
    "If you could have any dessert right now, what would it be?",
    "What's your favorite thing about where you grew up?",
    "If you could eliminate one thing from your daily routine, what would it be?",
    "What's the most spontaneous thing you've ever done?",
    "If you could master any instrument, which one would you choose?",
    "What's the best piece of advice you'd give to your younger self?",
    "If you could live in any fictional universe, where would you live?",
    "What's your favorite thing about yourself?",
    "If you could speak any language fluently, which one would it be?",
    "What's the most interesting place you've ever visited?",
    "If you could have any job for just one day, what would it be?",
    "What's the most impressive thing you know how to do?",
    "If you could trade lives with any person for a day, who would it be?",
    "What's your favorite childhood memory?",
    "If you could have any type of pet, exotic or not, what would you choose?",
    "What's the most inspiring thing you've ever seen or heard?",
    "If you could have any career, regardless of pay or talent required, what would you choose?",
    "What's your favorite way to spend a day off?",
    "If you could live in any city in the world, where would it be?",
    "What's the most important lesson life has taught you so far?",
    "If you could have dinner with any fictional character, who would it be and why?",
    "What's your favorite quote and why does it resonate with you?",
    "If you could have any career for a day, what would it be and why?",
    "What's the most memorable dream you've ever had?",
    "If you could instantly become fluent in any language, which one would you choose?",
    "What's your favorite board game or card game and why?",
    "If you could spend a day with any celebrity, who would it be and why?",
    "What's your favorite holiday and how do you typically celebrate it?",
    "If you could have any animal's ability, which one would you choose?",
    "What's the most courageous thing you've ever done?",
    "If you could have any view from your home, what would it be?",
    "What's the best piece of advice you've ever given?",
    "If you could have any job in the entertainment industry, what would it be?",
    "What's your favorite thing about the current season?",
    "If you could have any mythical creature as a pet, what would it be?",
    "What's the most interesting documentary you've ever watched?",
    "If you could have any fictional technology from a movie, what would it be?",
    "What's your favorite way to unwind after a stressful day?",
    "If you could have any food delivered to you right now, what would it be?",
    "What's your favorite memory from childhood?",
    "If you could live in any time period, past or future, which one would you choose?",
    "What's the most beautiful place you've ever visited?",
    "If you could be any fictional character for a day, who would you be?",
    "What's your favorite thing about your hometown?",
    "If you could have any piece of art in your home, what would it be?",
    "What's the most valuable lesson you've learned from a failure?",
    "If you could have any vehicle, real or fictional, what would it be?",
    "What's your favorite outdoor activity and why?",
    "If you could have any job in the medical field, what would it be?",
    "What's the most adventurous thing on your bucket list?",
    "If you could live in any country other than your own, where would it be?",
    "What's your favorite thing about being a part of your current community?",
    "If you could have any animal's intelligence, which one would you choose?",
    "What's your favorite way to spend a rainy day?",
    "If you could have any fictional character's wardrobe, whose would you choose?",
    "What's the most interesting fact you know?",
    "If you could have any historical figure as a mentor, who would it be?",
    "What's the best book you've read recently and why did you enjoy it?",
    "If you could have any animal's speed, which one would you choose?",
    "What's your favorite app on your phone and why?",
    "If you could have any movie director create a film about your life, who would it be?",
    "What's your favorite thing about your current job or studies?",
    "If you could have any superhero's sidekick, who would it be?",
    "What's the most unusual food you've ever tried?",
    "If you could live in any fictional universe, which one would you choose?",
    "What's your favorite form of exercise and why?",
    "If you could have any musician play at your birthday party, who would it be?",
    "What's your favorite thing about the city or town you live in?",
    "If you could have any chef cook you a meal, who would it be?",
    "What's the most beautiful piece of nature you've ever seen?",
    "If you could have any fantasy creature as a friend, who would it be?",
    "What's your favorite thing about your family?",
    "If you could have any superhero's powers, who would it be?",
    "What's the most interesting museum you've ever visited?",
    "If you could have any type of house, what would it look like?",
    "What's your favorite thing about your closest friend?",
    "If you could have any technology from a sci-fi movie, what would it be?",
    "What's the most valuable lesson you've learned from a success?",
    "If you could have any actor portray you in a movie, who would it be?",
    "What's your favorite thing about your current living situation?",
    "If you could have any animal's strength, which one would you choose?",
    "What's the most interesting thing you've learned recently?",
    "If you could have any video game character as a friend, who would it be?",
    "What's your favorite thing about the changing seasons?",
    "If you could have any type of business, what would it be?",
    "What's the most adventurous meal you've ever cooked?",
    "If you could have any historical figure as a friend, who would it be?",
    "What's your favorite thing about your daily routine?",
    "If you could have any creature from mythology as a pet, what would it be?",
    "What's the most impressive thing you've ever made or built?",
    "If you could have any author write a book about you, who would it be?",
    "What's your favorite thing about your favorite hobby?",
    "If you could have any famous person mentor you, who would it be?",
    "What's the most interesting thing you've seen on the internet recently?",
    "If you could have any animal's agility, which one would you choose?",
    "What's your favorite thing about your favorite holiday?",
    "If you could have any fictional character's abilities, whose would you choose?",
    "What's the most unusual job you've ever had or heard of?",
    "If you could have any movie character's wardrobe, whose would you choose?",
    "What's your favorite thing about your favorite food?",
    "If you could have any creature from a fantasy world as a friend, what would it be?",
    "What's the most interesting class you've ever taken?",
    "If you could have any musician write a song about you, who would it be?",
    "What's your favorite thing about your favorite TV show?",
    "If you could have any artist create a piece for you, who would it be?",
    "What's the most interesting place you've ever lived?",
    "If you could have any animal's senses, which one would you choose?",
    "What's your favorite thing about your favorite season?",
    "If you could have any celebrity teach you a skill, who would it be?",
    "What's the most interesting thing you've ever seen in person?",
    "If you could have any chef cook you a meal, who would it be?",
    "What's your favorite thing about your favorite book?",
    "If you could have any fictional character as a mentor, who would it be?",
    "What's the most interesting place you've ever worked?",
    "If you could have any historical figure as a mentor, who would it be?",
    "What's your favorite thing about your favorite movie?",
    "If you could have any video game character as a mentor, who would it be?",
    "What's the most unusual thing you've ever eaten?",
    "If you could have any famous person teach you a skill, who would it be?",
    "What's your favorite thing about your favorite sport?",
    "If you could have any fictional character as a friend, who would it be?",
    "What's the most interesting thing you've ever heard on a podcast?",
    "If you could have any musician write a song about you, who would it be?",
    "What's your favorite thing about your favorite music artist?",
    "If you could have any artist create a piece for you, who would it be?",
    "What's the most interesting thing you've ever seen in person?",
    "If you could have any chef cook you a meal, who would it be?",
    "What's your favorite thing about your favorite book?",
    "If you could have any fictional character as a mentor, who would it be?",
    "What's the most unusual thing you've ever eaten?",
    "If you could have any famous person teach you a skill, who would it be?",
    "What's your favorite thing about your favorite sport?",
    "If you could have any fictional character as a friend, who would it be?",
    "What's the most interesting thing you've ever heard on a podcast?"
]

class DailyQ(commands.Cog):

    """Cog for Toontown commands"""

    def __init__(self, bot):
        self.bot = bot
        self.daily_question.start()

    @tasks.loop(seconds=120)
    async def daily_question(self):
            now = datetime.now(pytz.timezone('US/Eastern'))
            if now.hour == 6 and now.minute == 0 :
                embed = discord.Embed(
                        title='Daily Question',
                        description=random.choice(icebreaker_questions),
                        colour=0x98FB98
                )
                embed.set_footer(text="Automated by Doopliss")
                channel = await self.bot.fetch_channel(1262547118430621806)
                await channel.send(embed=embed)

def setup(bot):
    bot.add_cog(DailyQ(bot))

def setup(bot):
    bot.add_cog(DailyQ(bot))
